version: '3.6'
networks:
  prod:
    driver: bridge

volumes:
  registry-stuff:
    driver: local
    
services:
  consul-service:
    container_name: consul-service
    image: consul
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_JOIN=consul-service
    networks:
      - prod    
    ports:
      - '8500:8500'
    expose:
      - "8500"
    volumes:
      - ./../data/consul-service/:/consul/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped

  rabbitmq-service:
    container_name: rabbitmq-service
    image: rabbitmq:3.6-management-alpine  
    networks:
      - prod 
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - "5672"
      - "15672"
    volumes:
      - ./../data/rabbitmq-service/:/var/lib/rabbitmq
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped

  # https://dev.mysql.com/doc/mysql-installation-excerpt/5.5/en/docker-mysql-getting-started.html
  # GENERATED ROOT PASSWORD: 5Ej%0gOmr3GJybaG8@t10fIh,YD
  mysql-service:
    container_name: mysql-service
    image: mysql/mysql-server:8.0.13
    networks:
      - prod 
    ports:
      - "3308:3306"
    expose:
      - "3308"
    volumes:
      - ./../data/mysql-service/:/var/lib/mysql-server
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped

  gateway-service:
    container_name: gateway-service
    image: mucunga90/gateway-service:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    expose:
      - "5000"
    networks:
      - prod
    volumes:
      - ./../data/gateway-service/:/var/log
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  
  user-service:
    container_name: user-service
    image: mucunga90/user-service:latest
    restart: unless-stopped
    ports:
      - '5001:5001'
    expose:
      - "5001"
    networks:
      - prod
    volumes:
      - ./../data/user-service/:/var/log
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - consul-service
      - rabbitmq-service
      - mysql-service
      - gateway-service
  

  