version: '3.7'

networks:
    public:
        driver: overlay
    private:
        driver: overlay

services:
    consul-service:
        image: consul
        environment:
            - CONSUL_BOOTSTRAP_EXPECT=1
            - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
            - CONSUL_DISABLE_KEYRING_FILE=true
        networks:
            - private
        ports:
            - '8500:8500'
        volumes:
            - './../data/consul-service/:/consul/data'
        deploy:
            replicas: 1
            restart_policy: {condition: on-failure, delay: 5s, max_attempts: 10}
            update_config: {parallelism: 1, delay: 10s, order: start-first}
        logging:
            options: {max-size: 10m, max-file: '10'}
            driver: json-file

    rabbitmq-service:
        image: 'rabbitmq:3.6-management-alpine'
        environment:
            RABBITMQ_DEFAULT_USER: appuser
            RABBITMQ_DEFAULT_PASS: appuser
        networks:
            - private
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - './../data/rabbitmq-service/:/var/lib/rabbitmq'
        deploy:
            replicas: 1
            restart_policy: {condition: on-failure, delay: 5s, max_attempts: 10}
            update_config: {parallelism: 1, delay: 10s, order: start-first}
        logging:
            options: {max-size: 10m, max-file: '10'}
            driver: json-file

    mysql-service:
        image: 'mysql:5.7'
        environment:
            MYSQL_USER: appuser
            MYSQL_PASSWORD: appuser
            MYSQL_ROOT_PASSWORD: root
        networks:
            - private
        ports:
            - '3308:3306'
        volumes:
            - './../data/mysql-service:/var/lib/mysql'
        deploy:
            replicas: 1
            restart_policy: {condition: on-failure, delay: 5s, max_attempts: 10}
            update_config: {parallelism: 1, delay: 10s, order: start-first}
        logging:
            options: {max-size: 10m, max-file: '10'}
            driver: json-file

    gateway-service:
        image: 'mucunga90/gateway-service:1.0.0'
        networks:
            - private
        ports:
            - '8080:8080'
        deploy:
            replicas: 1
            restart_policy: {condition: on-failure, delay: 30s, max_attempts: 10}
            update_config: {parallelism: 1, delay: 40s, order: start-first}
        logging:
            options: {max-size: 10m, max-file: '10'}
            driver: json-file

    user-service:
        image: 'mucunga90/user-service:1.0.0'
        networks:
            - private
        ports:
            - '5001:5001'
        deploy:
            replicas: 1
            restart_policy: {condition: on-failure, delay: 30s, max_attempts: 10}
            update_config: {parallelism: 1, delay: 40s, order: start-first}
        logging:
            options: {max-size: 10m, max-file: '10'}
            driver: json-file

    alert-service:
        image: 'mucunga90/alert-service:1.0.0'
        networks:
            - private
        ports:
            - '5002:5002'
        deploy:
            replicas: 1
            restart_policy: {condition: on-failure, delay: 30s, max_attempts: 10}
            update_config: {parallelism: 1, delay: 40s, order: start-first}
        logging:
            options: {max-size: 10m, max-file: '10'}
            driver: json-file

    web-service:
        image: 'mucunga90/web-service:1.0.0'
        networks:
            - private
            - public
        ports:
            - '80:80'
        deploy:
            replicas: 1
            restart_policy: {condition: on-failure, delay: 30s, max_attempts: 10}
            update_config: {parallelism: 1, delay: 40s, order: start-first}
        logging:
            options: {max-size: 10m, max-file: '10'}
            driver: json-file
