server:
    port: '${PORT:5002}'
eureka:
    instance:
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    server:
        peer-node-read-timeout-ms: 300000
        enable-self-preservation: false
    client:
        enabled: true
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
spring:
    rabbitmq:
        port: 5672
        host: 192.168.100.29
        username: appuser
        password: appuser
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: 'jdbc:mysql://192.168.100.29:3308/alert_service?useSSL=false&serverTimezone=UTC&autoReconnect=true'
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: 'SELECT 1'
        max-active: 15
        max-idle: 10
        max-wait: 8000
    mail:
        host: smtp.gmail.com
        port: 587
        username: mucunga90
        password: Mucunga90()
        properties.mail.smtp.user: true
        properties.mail.smtp.starttls.enable: true
        smtp.debug: true
        batchSize: 10
        subject: MALI
        fixedDelay: 5000
        initialDelay: 5000
        verificationLink: 192.168.100.29/user/verify
flyway:
    enabled: true
    url: 'jdbc:mysql://192.168.100.29:3308/mysql'
    schemas: alert_service
    user: root
    password: root
management:
    metrics.tags.application: ${spring.application.name}
    endpoints.web.exposure.include: prometheus
