server:
  port: ${PORT:8802}

eureka:
  instance:
    hostname: 192.168.100.29
    preferIpAddress: true
  server:
    enableSelfPreservation: true
    eviction-interval-timer-in-ms: 1000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

