server:
    port: '${PORT:8080}'
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
    level:
        root: INFO
        org.springframework.web: INFO
        org.spring-boot-starter-actuator: DEBUG
        org.springframework.security: DEBUG
        org.spring-cloud-starter-sleuth: DEBUG
        org.spring-cloud-starter-netflix-zuul: DEBUG
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    server:
        enableSelfPreservation: false
    client:
        serviceUrl:
            defaultZone: 'http://192.168.100.29:8761/eureka/'
zuul:
    routes:
        auth-service:
            path: '/auth/**'
            service-id: AUTH-SERVICE
            strip-prefix: false
            sensitive-headers: 'Cookie,Set-Cookie'
        user-service:
            path: '/user/**'
            service-id: user-service
    host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000
