server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<path>.*), /$\{path}
      - id: advert-service
        uri: lb://advert-service
        predicates:
        - Path=/advert/**
        filters:
        - RewritePath=/advert/(?<path>.*), /$\{path}
      - id: payment-service
        uri: lb://payment-service
        predicates:
        - Path=/payment/**
        filters:
        - RewritePath=/payment/(?<path>.*), /$\{path}
      - id: alert-service
        uri: lb://alert-service
        predicates:
        - Path=/alert/**
        filters:
        - RewritePath=/alert/(?<path>.*), /$\{path}
      - id: document-service
        uri: lb://document-service
        predicates:
        - Path=/document/**
        filters:
        - RewritePath=/document/(?<path>.*), /$\{path}
      - id: report-service
        uri: lb://report-service
        predicates:
        - Path=/report/**
        filters:
        - RewritePath=/report/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs