debug: true

server:
  port: 5003

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.29:5002/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service
    customer:
      path: /customer/**
      serviceId: customer-service
    advert:
      path: /advert/**
      serviceId: advert-service
    payment:
      path: /payment/**
      serviceId: payment-service
    alert:
      path: /alert/**
      serviceId: alert-service
    document:
      path: /document/**
      serviceId: document-service
    report:
      path: /report/**
      serviceId: report-service