server:
    port: '${PORT:5003}'
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    server:
        enableSelfPreservation: false
    client:
        serviceUrl:
            defaultZone: 'http://192.168.100.29:8761/eureka/'
spring:
    rabbitmq:
        port: 5672
        host: 192.168.100.29
        username: appuser
        password: appuser
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: 'jdbc:mysql://192.168.100.29:3308/user_service?useSSL=false&serverTimezone=UTC&autoReconnect=true'
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: 'SELECT 1'
        max-active: 15
        max-idle: 10
        max-wait: 8000
flyway:
    enabled: true
    url: 'jdbc:mysql://192.168.100.29:3308/mysql'
    schemas: user_service
    user: root
    password: root
management:
    metrics.tags.application: ${spring.application.name}
    endpoints.web.exposure.include: prometheus
