filebeat.inputs:
- type: container
  stream: all
  exclude_files: ['\.gz$']
  paths:
    - '/var/lib/docker/containers/*/*.log'
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  ignore_older: 30m
  scan_frequency: 5m
  harvester_limit: 1
  close_inactive: 10s
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["192.168.100.29:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false

# ILM setup
# ---------
setup.ilm.enabled: auto
setup.ilm.rollover_alias: "filebeat"
ilm.enabled: false