filebeat.inputs:
- type: container
  stream: stdout
  paths:
    - "/var/log/containers/*.log"
  multiline.pattern: '^@.*message\ EventError.*'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 14
  ignore_older: 30m
  scan_frequency: 5m
  harvester_limit: 1
  close_inactive: 10s


processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["192.168.100.29:9200"]
  indices:
    - index: "filebeat"

logging.json: true
logging.metrics.enabled: false

# ILM setup
# ---------
setup.ilm.enabled: false
ilm.enabled: false