version: '3.7'
services:
    rabbitmq:
        image: 'rabbitmq:3.6-management-alpine'
        environment:
            RABBITMQ_DEFAULT_USER: appuser
            RABBITMQ_DEFAULT_PASS: appuser
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]

    mysql:
        image: 'mysql:5.7'
        environment:
            MYSQL_USER: appuser
            MYSQL_PASSWORD: appuser
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3308:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]

    # Monitoring the system
    grafana:
        image: grafana/grafana:6.2.2
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/influxdb
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin1234
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]

    prometheus:
        image: prom/prometheus:v2.17.2
        ports:
            - 9090:9090
        volumes:
            - $MALI/docker/config/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]

    node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]

    cadvisor:
        image: google/cadvisor:latest
        ports:
            - '9101:8080'
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]

     # Logging the system
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.4'
        environment:
            - "discovery.type=single-node"
        ports:
            - '9200:9200'
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]

    kibana:
        image: 'docker.elastic.co/kibana/kibana:6.5.4'
        ports:
            - '5601:5601'
        environment:
            - "xpack.security.enabled=false"
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - elasticsearch

    logstash:
        image: 'docker.elastic.co/logstash/logstash:6.5.4'
        ports:
            - "5044:5044"
        volumes:
            - logstash_data:/logs
            - $MALI/docker/config/logstash.conf:/conf/logstash.conf
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - elasticsearch

    # Mali microservices
    config-service:
        image: 'mucunga90/config-service:1.0.1'
        ports:
            - '8888:8888'
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    discovery-service:
        image: 'mucunga90/discovery-service:1.0.0'
        ports:
            - '8761:8761'
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - rabbitmq
            - mysql
            - config-service
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    auth-service:
        image: 'mucunga90/auth-service:1.0.0'
        ports:
            - '5001:5001'
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - rabbitmq
            - mysql
            - config-service
            - discovery-service
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    gateway-service:
        image: 'mucunga90/gateway-service:1.0.0'
        ports:
            - '8080:8080'
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - rabbitmq
            - mysql
            - config-service
            - discovery-service
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    alert-service:
        image: 'mucunga90/alert-service:1.0.1'
        ports:
            - '5002:5002'
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - rabbitmq
            - mysql
            - config-service
            - discovery-service
            - gateway-service
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    user-service:
        image: 'mucunga90/user-service:1.0.1'
        ports:
            - '5003:5003'
        networks:
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - rabbitmq
            - mysql
            - config-service
            - discovery-service
            - gateway-service
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    web-service:
        image: 'mucunga90/web-service:1.0.0'
        ports:
            - '80:80'
        networks:
            - frontend-tier
            - backend-tier
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
            placement:
                constraints: [node.role == manager]
        depends_on:
            - rabbitmq
            - mysql
            - config-service
            - discovery-service
            - auth-service
            - gateway-service
            - alert-service
            - user-service


networks:
    frontend-tier:
        driver: overlay
        attachable: true
    backend-tier:
        driver: overlay
        attachable: true

volumes:
    rabbitmq_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $MALI/docker/data/rabbitmq
    mysql_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $MALI/docker/data/mysql
    elasticsearch_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $MALI/docker/data/elasticsearch
    logstash_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $MALI/docker/data/logstash
    influxdb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $MALI/docker/data/influxdb
    grafana_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $MALI/docker/data/grafana
    filebeat_data:
            driver: local
            driver_opts:
                type: none
                o: bind
                device: $MALI/docker/data/filebeat
    prometheus_data:
            driver: local
            driver_opts:
                type: none
                o: bind
                device: $MALI/docker/data/prometheus
