version: '3.7'
services:
    consul-service:
        image: consul
        environment:
            - CONSUL_BOOTSTRAP_EXPECT=1
            - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
            - CONSUL_DISABLE_KEYRING_FILE=true
        ports:
            - '8500:8500'
        logging:
            options: {max-size: 10m, max-file: '10'}
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10

    rabbitmq-service:
        image: 'rabbitmq:3.6-management-alpine'
        environment:
            RABBITMQ_DEFAULT_USER: appuser
            RABBITMQ_DEFAULT_PASS: appuser
        ports:
            - '5672:5672'
            - '15672:15672'
        logging:
            options: {max-size: 10m, max-file: '10'}
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10

    mysql-service:
        image: 'mysql:5.7'
        environment:
            MYSQL_USER: appuser
            MYSQL_PASSWORD: appuser
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3308:3306'
        logging:
            options: {max-size: 10m, max-file: '10'}
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10

    web-service:
        image: 'mucunga90/web-service:1.0.0'
        ports:
            - '80:80'
        logging:
            options: {max-size: 10m, max-file: '10'}
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
        depends_on:
            - consul-service
            - mysql-service
            - rabbitmq-service

    gateway-service:
        image: 'mucunga90/gateway-service:1.0.0'
        ports:
            - '8080:8080'
        logging:
            options: {max-size: 10m, max-file: '10'}
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
        depends_on:
            - consul-service
            - mysql-service
            - rabbitmq-service

    user-service:
        image: 'mucunga90/user-service:1.0.0'
        ports:
            - '5001:5001'
        logging:
            options: {max-size: 10m, max-file: '10'}
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
        depends_on:
            - consul-service
            - mysql-service
            - rabbitmq-service

    alert-service:
        image: 'mucunga90/alert-service:1.0.0'
        ports:
            - '5002:5002'
        logging:
            options: {max-size: 10m, max-file: '10'}
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 10
        depends_on:
            - consul-service
            - mysql-service
            - rabbitmq-service
