spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/alert/**
          filters:
            - RewritePath=/alert/(?<path>.*), /$\{path}