spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**
          filters:
            - RewritePath=/email/(?<path>.*), /$\{path}